package fr.endoskull.cosmetics.utils;

import fr.endoskull.api.commons.lang.MessageUtils;

public enum CosmeticsMessage implements MessageUtils {
    GUI_TAG, TAG_CHANGE, TAG_ANVIL, GUI_COSMETICS, TAGS, TAGS_DESC, PARTICLES, MUSICS, MUSICS_DESC,
    GUI_MUSICS, STOP_MUSIC, YOU_STOP_MUSIC, GUI_PARTICLES, SHOW_PARTICLES, HIDE_PARTICLES, YOU_SHOW_PARTICLES,
    YOU_HIDE_PARTICLES, PARTICLE_SELECTED, PARTICLE_SELECT, YOU_SELECT_PARTICLE, PARTICLE_PRICE,
    P_WHISP, P_WHISP_DESC, P_SCANNER, P_SCANNER_DESC, P_SPIRAL, P_SPIRAL_DESC, P_WHIRLWIND, P_WHIRLWIND_DESC,
    P_SPEED, P_SPEED_DESC, P_JUMP, P_JUMP_DESC, P_HELICOPTER, P_HELICOPTER_DESC, P_REACTOR, P_REACTOR_DESC,
    P_DOUBLE_JUMP, P_DOUBLE_JUMP_DESC, P_FLY, P_FLY_DESC, P_INFINITE_JUMP, P_INFINITE_JUMP_DESC,
    REMOVE_PARTICLE, YOU_REMOVE_PARTICLE, GUI_PARTICLE_CONFIRM, PARTICLE_BUY, PARTICLE_LESS_MONEY, YOU_BUY_PARTICLE,
    CANCEL, MUSIC_PLAYING, DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE,
    PINK, PURPLE, WHITE, GRAY, DARK_GRAY, BLACK;

    private final static String path = "cosmetics";

    @Override
    public String getPath() {
        return path + "." + this.toString().toLowerCase().replace("_", "-");
    }
}
