name: EndoSkullCosmetics
version: 1.0
author: BebeDlaStreat
main: fr.endoskull.cosmetics.Main
description: Plugin de cosmetiques pour EndoSkull
website: https://endoskull.fr
commands:
  pets:
    permission: endoskull.pets
    aliases: [pet]
    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  particules:
    permission: endoskull.particles
    aliases: [particles]
    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  cosmetics:
    permission: endoskull.cosmetics
    aliases: [cosmetiques]
    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  tag:
    permission: endoskull.tag
    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  nick:
    permission: endoskull.nick
    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  music:
    permission: endoskull.music