name: EndoSkullCosmetics
version: 1.0
author: BebeDlaStreat
main: fr.endoskull.cosmetics.Main
depend:
  - EndoSkullCore
commands:
  particules:
    aliases: [particles]
  cosmetics:
    aliases: [cosmetiques]
  tag:
    permission: endoskull.tag
#    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"
  music:
    aliases: [musique, musics, musiques]
    permission: endoskull.music
#    permission-message: "§cVous n'avez pas le grade requis, rendez-vous sur https://store.endoskull.fr"